# Generated by Django 3.0.8 on 2020-08-04 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsets',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
    ]
